#

- hosts: lab-private

  tasks:
  - name: "Setup vars"
    include_vars: vars/base_vars.yml

  - name: "Set envionment proxy Config"
    template: src=templates/environment.j2  dest=/etc/environment
    become: true

  - name: "Set yum proxy Config"
    template: src=templates/yum.conf.j2  dest=/etc/yum.conf
    become: true


